# alias
alias ..='cd ../'
alias ...='cd ../../'
alias backup='$HOME/bin/backup.sh'
alias cal='cal -m'
alias clang-format='clang-format -i -style=file'
alias dotf='git --git-dir=$HOME/.dotf --work-tree=$HOME'
alias gpull='git pull origin main'
alias gpush='git push origin main'
alias la='ls --all --color'
alias ls='ls --color'
alias main='abduco -A main'
alias mkdir='mkdir -p'
alias npmglist='npm list -g --depth 0'
alias reload='. $HOME/.bashrc'
alias restore='$HOME/bin/restore.sh'
alias rm='rm -riv'
alias sgit='ssh -T git@github.com'
